/*
-- Query: SELECT * FROM boligramaDB.ueas
LIMIT 0, 1000

-- Date: 2012-12-03 21:03
*/
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (101,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (102,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (103,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (104,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (111,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (112,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (113,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (114,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (121,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (122,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (123,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (124,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (181,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (182,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (183,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (184,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (191,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (192,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (193,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (194,'Optativa','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (251,'Optativa 1','CBS',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (252,'Optativa 2','CBS',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (253,'Optativa 3','CBS',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (281,'Temas selectos 1','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (291,'Temas selectos 2','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (301,'Seminario de investigacion 1','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (312,'Seminario de investigacion 2','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (323,'Seminario de unvestigacion 3','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (111111,'Optativa','CBI',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (211012,'Fundamentos de fisica','CBS',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (213024,'Matematicas 2','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (213025,'Matematicas 3','CBS',11,0);

INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (213244,'Estadistica 1','CSH',9,0);

INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221175,'Administracion general','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221176,'Historia general de la empresa y sociedad org','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221177,'Modelacion cuantitativa en las organizaciones','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221178,'Teoria administrativa','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221179,'Organizacion del trabajo y comportamiento hum','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221180,'Modelacion cuantitativa en las organizaciones','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221181,'Teoria de la organizacion','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221182,'Sociedad de consumo, desarrollo tecnologico y','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221183,'Informacion financiera','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221185,'Comportamiento en las organizaciones','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221186,'Accion estatal y gestion social','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221187,'Contabilidad administrativa','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221188,'Informatica','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221189,'Direccion y administracion de personal','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221190,'Etica y responsabilidad social','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221191,'Fundamentos de politica economica','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221192,'Analisis de decisiones','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221193,'Marketing 1','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221194,'Gestion y control estrategicos 1','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221195,'Administracion financiera 1','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221196,'Marketing 2','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221197,'Gestion y control estrategicos 2','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221198,'Administracion de operaciones','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221199,'Administracion financiera 2','CSH',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221200,'Problemas filosoficos y civilizacion occident','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221201,'Derecho 1','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (221202,'Derecho 2','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (222222,'Optativa','CBI',9,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (224188,'Introduccion a la microeconomia','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (225035,'Teoria y problemas sociopoliticos contemporan','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (225036,'Historia contemporanea de Mexico','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (225037,'Argumentacion y conocimiento','CSH',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (225564,'Ingles intermedio 1','CSH',10,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (225565,'Ingles intermedio 2','CSH',10,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (225566,'Ingles intermedio 3','CSH',10,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230025,'Bioquímica 2','CBS',14,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230026,'Bioquimica 3','CBS',14,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230027,'Biologia celular','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230028,'Biologia general','CBS',12,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230029,'Quimica general','CBS',14,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230030,'Introduccion a la computacion','CBS',6,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230031,'Quimica organica I','CBS',15,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (230032,'Bioquimica 1','CBS',14,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231170,'Seminario de investigacion 1','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231171,'Seminario de investigacion 2','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231172,'Seminario de investigacion 3','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231173,'Biometria 1','CBS',10,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231174,'Biometria 2','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231175,'Botanica 2','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231176,'Botanica 3','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231177,'Micologia','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231178,'Zoologia 4','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231179,'Tipos de vegetacion en Mexico','CBS',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231180,'Biologia tisular','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231181,'Zoogeografia de Mexico','CBS',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231183,'Sistematica','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231184,'Bioconservacion','CBS',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231202,'Ecologia 1','CBS',10,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231203,'Fitogeografia de Mexico','CBS',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231211,'Zoologia 1','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231212,'Botanica 1','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231221,'Paleontologia','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231222,'Anatomia comparativa de vertebrados','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231223,'Anatomia vegetal','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231224,'Biogeografia','CBS',8,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231226,'Climatologia','CBS',7,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231228,'Fisiologia vegeta','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231232,'Edafologia','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231236,'Manejo de Ecosistemas','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231239,'Fisiologia de vertebrados','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231240,'Zoologia 2','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231241,'Zoologia 3','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231243,'Ecologia 2 poblaciones','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231244,'Ecologia 3 comunidades','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (231246,'Evolucion','CBS',12,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (234121,'Genetica general','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (235133,'Geologia','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (213033,'Matematicas 1','CBS',11,0);
INSERT INTO `ueas` (`idueas`,`nombre`,`division`,`creditos`,`estado`) VALUES (214007,'Fisicoquimica 1','CBS',10,0);


